name: Main

on:
  push:
    branches:
      - main

env:
  RUBY_VERSION: '3.2'

permissions:
  id-token: write
  contents: read

jobs:
  rubocop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version:  ${{ env.RUBY_VERSION }}
          bundler-cache: true
      - run: bundle exec rubocop

  rspec:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version:  ${{ env.RUBY_VERSION }}
          bundler-cache: true
      - run: bundle exec rake spec
        env:
          LINE_CHANNEL_ID: ${{ secrets.LINE_CHANNEL_ID }}
          LINE_CHANNEL_TOKEN: ${{ secrets.LINE_CHANNEL_TOKEN }}
          LINE_CHANNEL_SECRET: ${{ secrets.LINE_CHANNEL_SECRET }}

  cucumber:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version:  ${{ env.RUBY_VERSION }}
          bundler-cache: true
      - run: bundle exec rake cucumber
        env:
          LINE_CHANNEL_ID: ${{ secrets.LINE_CHANNEL_ID }}
          LINE_CHANNEL_TOKEN: ${{ secrets.LINE_CHANNEL_TOKEN }}
          LINE_CHANNEL_SECRET: ${{ secrets.LINE_CHANNEL_SECRET }}

  deploy:
    runs-on: ubuntu-latest
    needs:
      - rubocop
      - rspec
      - cucumber
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v3
      - uses: aws-actions/setup-sam@v2
      - uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.DEPLOY_ROLE }}
          aws-region: ap-northeast-1
      - run: sam build --parallel --use-container --cached
      - run: |
          sam deploy --no-confirm-changeset --no-fail-on-empty-changeset \
            --parameter-overrides "CertificateArn=${{ secrets.CERTIFICATE_ARN }}" \
            --parameter-overrides "LINE_CHANNEL_ID=${{ secrets.LINE_CHANNEL_ID }}" \
            --parameter-overrides "LINE_CHANNEL_TOKEN=${{ secrets.LINE_CHANNEL_TOKEN }}" \
            --parameter-overrides "LINE_CHANNEL_SECRET=${{ secrets.LINE_CHANNEL_SECRET }}"
